### ISSUE TITLE
Issue published in the wrong repository

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/docbot#21]
Commit https://github.com/tarantool/tarantool-ee/commit/9b45c13889cc086fb24f97fb111d4d518378bc3c was merged recently, and the resulting issue was opened in `https://github.com/tarantool/doc/issues/2982` (https://github.com/tarantool/doc/issues/2982), not in the enterprise repository. (It was moved afterwards, so now it's at the right place.

Please test and fix repository selection.

**Comment by artembo** [comment]
Can anyone check the service is working properly? I re-deliver webhook related to this [commit](https://github.com/tarantool/tarantool-ee/commit/9b45c13889cc086fb24f97fb111d4d518378bc3c) and the [issue](https://github.com/tarantool/enterprise_doc/issues/184) appeared.

The problem was in a failed deployment of the service.

**Comment by Totktonada** [comment]
If the re-deliver works, I don't see a reason why new delivers will not work.

**Comment by artembo** [comment]
@Totktonada Thanks!
